import type { Metadata } from "next";

import "./globals.css";
import { TolgeeNextProvider } from "@/tolgee/client";
import { getStaticData } from "@/tolgee/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const staticData = await getStaticData([locale]);

  return (
    <html lang="en">
      <body>
        <TolgeeNextProvider language={locale} staticData={staticData}>
          {children}
        </TolgeeNextProvider>
      </body>
    </html>
  );
}
